baseURL = "http://example.org/"
languageCode = "en-us"
title = "hughsambros."
theme = "osaron"
disqusShortname = "hughsambros"
[taxonomies]
    tag = "tags"
    category = "categories"

[permalinks]
    blog = "/:section/:year/:month/:title/"
    about = "/:section/:slug"
    contact = "/:section/:slug"
