baseURL = "https://www.hughsambros.com/"
languageCode = "en-us"
title = "hughsambros."
theme = "osaron"
disqusShortname = "hughsambros"
paginate = 5

[params]
    facebookLink = "https://www.facebook.com/hughsambros/"
    youtubeLink = "https://www.youtube.com/"
    instagramLink = "https://www.instagram.com/hughsambros/"
[taxonomies]
    tag = "tags"
    category = "categories"

[permalinks]
    blog = "/:section/:year/:month/:filename/"
    singles = "/:filename/"
