backend:
  name: git-gateway
  repo: nicholasjhs/hughsambros # Path to your Github repository
  branch: development # Branch to update (master by default)

media_folder: "themes/osaron/static/assets/images/originals" # specifies where uploaded files will be saved in the repo
public_folder: "/assets/images/originals" # indicates where they can be found in the published site
publish_mode: editorial_workflow

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "publishdate", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Author", name: "author", widget: "select", options: ["Nicholas Hugh Sam", "Alexander Hugh Sam", "Hugh Sam Bros"]}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Featured Image", name: "img", widget: "image", required: false}
      - {label: "Link", name: "slug", widget: "string", default: "this-is-an-example", pattern: ["^[a-z0-9]+(?:-[a-z0-9/]+)*$", "Use this format: nkc0-this-is-an-example"]}
      - {label: "Short Title", name: "shorttitle", widget: "string", required: false}
      - {label: "Categories", name: "categories", widget: "list", required: false}
      - {label: "Tag", name: "tags", widget: "list", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "singles" # Used in routes, e.g., /admin/collections/blog
    label: "Page" # Used in the UI
    folder: "content/singles" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
        preview: false
    fields: # The fields for each document, usually in front matter
      - {label: "Page Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "publishdate", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Featured Image", name: "background", widget: "image", required: false}
      - {label: "Link", name: "slug", widget: "string", default: "this-is-an-example", pattern: ["^[a-z0-9]+(?:-[a-z0-9/]+)*$", "Use this format: nkc0-this-is-an-example"]}
      - {label: "Body", name: "body", widget: "markdown"}
