backend:
  name: git-gateway
  repo: nicholasjhs/hughsambros # Path to your Github repository
  branch: development # Branch to update (master by default)

media_folder: "themes/osaron/static/images/hsb" # Folder where user uploaded files should go
public_folder: "/images/hsb" # The src attribute for uploaded media will begin with
publish_mode: editorial_workflow

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "New Post" # Used in the UI
    folder: "content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{filename}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "publishdate", widget: "datetime", format: "YYYY-MM-DD hh:mma"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Author", name: "author", widget: "select", options: ["Nicholas Hugh Sam", "Alexander Hugh Sam", "Hugh Sam Bros"]}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Image", name: "img", widget: "image"}
      - {label: "Link", name: "slug", widget: "string", default: "this-is-an-example", pattern: ["^[a-z0-9]+(?:-[a-z0-9/]+)*$", "Use this format: nkc0-this-is-an-example"]}
      - {label: "Filename", name:"filename", widget: "string", default: "nkc#0-this-is-an-example"}
      - {label: "Short Title", name: "shorttitle", widget: "string"}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Tag", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
